version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: MindStore_API
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MindStoreDB
    restart: always
    #env_file: #para criar variaveis de environment
    #- .env
    volumes: #para ficar com a data no pc mesmo que elimine o container
      - ./db-data/:/var/lib/postgresql/data/